### ISSUE TITLE
For test failures, should we show the actual and expected values?

### ISSUE THREAD

**Issue by glennj** [exercism/8th#105]
With a few small changes to the exercism/test library, we can achieve this.

Some example output:

![image](https://github.com/exercism/8th/assets/122470/32e429ca-aa07-4aa9-af02-f36c25f7c581)

![image](https://github.com/exercism/8th/assets/122470/df626287-8a2f-429a-8629-1de7de3bfeeb)

![image](https://github.com/exercism/8th/assets/122470/4b6ad877-01f8-4a2c-9240-68da74a315c4)

![image](https://github.com/exercism/8th/assets/122470/c7a90177-668e-4694-a168-e6a6ee17b1e0)

![image](https://github.com/exercism/8th/assets/122470/26e0c05a-7080-4915-ae1f-63b4e957ba8c)

@axtens @softmoth 
Is it a good idea?
Do you like the output (particularly, opinions about the angle quotes)?

**Comment by axtens** [comment]
Chevrons are cool and are used in other places as "really obvious quotation marks". In this PR what's not to like?

**Comment by softmoth** [comment]
It's great! I can imagine if the expected value is very long, it might be nice to have truncated, but that can be dealt with at a later time if the need crops up.

**Comment by axtens** [comment]
Which, when you get to that, should be a middle truncation e.g. tru..ion
