### ISSUE TITLE
Actual and expected values are swapped

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/8th#132]
When a test fails, the actual and expected values are swapped.

E.g., try using this (wrong) implementation for `sieve`:

```8th
: primes \ n -- a
  drop [1]
;
```

The output is:

```8th
    Actual:    « [1]»
    Expected:  «1»
```

@axtens is this something you can fix?

**Comment by axtens** [comment]
You'll have to give me more context. As defined, you've created a word that purports to find a number of the stack and replace it with an array. And in the body of the definition you `drop` the number and then push a single-element array containing 1 in its 0-th element.

**Comment by axtens** [comment]
And `bin/run-no-docker sieve` passes everything. Are you asking for a test that will fail?

**Comment by axtens** [comment]
```
"must fail"
    [1]
    ( 1 primes )
    equal?
```
must fail  ... FAIL
    Actual:    « []»
    Expected:  « [1]»

```

**Comment by axtens** [comment]
So not sure what you're asking

**Comment by ErikSchierboom** [comment]
It's probably an issue on my side, sorry!
