### ISSUE TITLE
Failing test name not printed when stack is not of expected size

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/8th#133]
When a test fails and the stack is not of the size expected by the tests, the test name is not printed.

E.g., try using this (wrong) implementation for `sieve`:

```8th
: primes \ n -- a
  [1]
;
```

```
 []  ... FAIL
    Actual:    « [1]»
    Expected:  «1»
```

However, changing it to:

```8th
: primes \ n -- a
  drop [1]
;
```

does output the test name:

```8th
no primes under two  ... FAIL
    Actual:    « [1]»
    Expected:  « []»
```

@axtens is this something you can fix?

**Comment by glennj** [comment]
Hmm, maybe we could use variables for the test name and the expected values

**Comment by axtens** [comment]
Funny. Lispers talk about hygienic macros, and forthers about hygienic
stack. You can't have varargs for FORTH words. This is why two-fer requires
a null for the missing name.
In another place recently I wrote,

> It dawned on me recently why so many people coming from algorithmic
languages struggle with FORTH and its dialects: parameters are implicit. In
algorithmic languages, parameters are explicit, named and sometimes typed,
whereas that FORTH's ROT expects at least three items on the stack is
nowhere obvious except in the documentation.

So I'm of the opinion that this is not fixable ... unless we completely
revamp the test framework. perhaps creating a test DSL and implementing it
with G:parsews and G:parseln

**Comment by ErikSchierboom** [comment]
Maybe we could have a specific error message when the stack is not the expected size and then print the stack as the actual value?

**Comment by axtens** [comment]
I'd be interested in @glennj 's opinion. I suppose, given that the test is
the top most, ring-0 in a sense, then yes we could check for depth less
than three and dump the stack. Out in the "real world" however I'd be ...
umm ... reticent to agree

**Comment by glennj** [comment]
Let me see if I can fit a check in there.

**Comment by glennj** [comment]
Parenthetically, fixing this will prevent people abusing 8th, like this two-for solution:
![image](https://github.com/exercism/8th/assets/122470/f9e69664-3b3e-4c91-8668-0f6f65f1f223)

**Comment by axtens** [comment]
Yes, I had a similar "abuse the test framework" experience a few months back.  Give it your best shot.
