### ISSUE TITLE
Extra space displayed in test output for array values

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/8th#134]
When a test fails for an array value, the actual and expected value have a leading space that isn't there for other data types:

```8th
no primes under two  ... FAIL
    Actual:    « [1]»
    Expected:  « []»
```

Compared to:

```8th
1 is decimal 1  ... FAIL
    Actual:    «1»
    Expected:  «2»
```

@axtens is this something you can fix?

**Comment by axtens** [comment]
Ah now this makes more sense. Is this the same as the other issue I've been responding to?

**Comment by axtens** [comment]
Have asked on the 8th forum: https://8th-dev.com/forum/index.php?board=28.0

**Comment by axtens** [comment]
Got an answer on that: stringifying an array adds a leading space. I'll fix the lib sometime this week

**Comment by axtens** [comment]
Related to? https://github.com/exercism/8th/issues/134

**Comment by axtens** [comment]
Discussed on the forum at https://forum.exercism.org/t/leading-space-on-array-output-in-8th/10779

**Comment by axtens** [comment]
Being addressed by https://github.com/exercism/8th/pull/135
