### ISSUE TITLE
Possible small documentation change

### ISSUE THREAD

**Issue by Fepelus** [exercism/8th#90]
The instructions that are shown with every exercise include this section (example from hello-world):

> From a REPL
> 
> Start 8th loading test-words.8th and your solution file: 8th -f test-words.8th -f hello-world-tests.8th This will start a CLI session where you can run tests interactively by copying and pasting them in from hello-world-tests.8th or by entering your own.

Running `8th -f test-words.8th -f hello-world-tests.8th` throws an exception on my CLI session because the `hello-world` word has not been loaded, of course. I presume this ought to be `8th -f test-words.8th -f hello-world.8th` and hello-world-tests.8th should not be loaded so that you can follow the instruction later in the paragraph to copy and paste in code from that file.

If my presumption is correct and you agree that this ought to be changed I can bang through all the `/exercises/practice/*/.docs/instructions.append.md` files and make a PR changing them if that would be helpful. (It would only be a small contribution: I have found the documentation on this track particularly useful.)

**Comment by axtens** [comment]
Interesting. Please can you tell me what version of 8th you're using? I haven't updated the binary that the UX is using for a few months. We may have a regression here.

**Comment by Fepelus** [comment]
Oh thanks for looking at this!

My `8th -v` gives `8th 23.06 MACOS64 Free (1a7d5fe0/2023-08-02)`

**Comment by Fepelus** [comment]
And just to share what I'm seeing:

> fepelus@pbmbp> `cd Exercism/8th/hello-world`
> fepelus@pbmbp hello-world> `cat README.md`
> [... bunch of stuff elided]
> From a REPL
> 
> Start 8th loading test-words.8th and your solution file:
> 8th -f test-words.8th -f hello-world-tests.8th
> This will start a CLI session where you can run tests interactively by copying and pasting them in from hello-world-tests.8th or by entering your own. 
> [... more elided]
> fepelus@pbmbp hello-world> `8th -f test-words.8th -f hello-world-tests.8th`
> Exception: Unknown hello-world: at line 0 byte 49 in /Users/paddy/Exercism/8th/hello-world/hello-world-tests.8th: G:sthrow: task REPL
>
> fepelus@pbmbp hello-world> `8th -f test-words.8th -f hello-world.8th`      
> 8th 23.06 MACOS64 Free (1a7d5fe0/2023-08-02) custid: 52359c72
> 
> ok>

**Comment by axtens** [comment]
It is a regression but not on the binary side. The instructions re `8th
test.8th` still apply but the instructions for working from within a REPL
are clearly wrong and I'm the culprit.

If you have time please raise a PR that encourages the student, having
defined their `hello-world` word to `f:include` the test words and the the
tests set. Essentially, the student has to do what's done in `test.8th`. As
you pointed out, the tests assume the presence of the word to be tested and
things fall over if it's not there.

Kind regards,
Bruce
